spring.application.name=backend

# --- Base de datos PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/raeesmart
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Microservicio de IA ---
raeesmart.ia.base-url=http://127.0.0.1:8000

# --- Almacenamiento de fotos ---
raeesmart.almacenamiento.directorio=./uploads/raee-smart

# --- JWT ---
raeesmart.jwt.secret=cambia-esta-clave-por-una-propia-de-al-menos-32-caracteres
raeesmart.jwt.expiration-ms=86400000

# --- CORS
raeesmart.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:19006,http://127.0.0.1:8000

# --- Subida de archivos ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
